backend/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

Auth::routes(['register' => false]);

Route::get('/', function() {
    if(Auth::guest()) {
        return view('auth.login');
    } else {
        return redirect('events');
    }
});
Route::resource('/events', 'EventController')->middleware('auth');
Route::get('/events/{event}/attendees', 'EventController@showAttendeeList')->name('events.attendees')->middleware('auth');
Route::get('/events/{event}/rating', 'EventController@showEventRating')->name('events.rating')->middleware('auth');

backend/app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    protected $hidden = [];
    protected $guarded = ['updated_at', 'created_at'];
    public $timestamps = false;

    public function sessions() {
        return $this->hasMany('App\Session');
    }

    public function ratings() {
        return $this->hasMany(AttendeeRegistration::class,'event_id');
    }
}

backend/app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Event;
use App\Session;
use App\User;
use Illuminate\Http\Request;

class EventController extends Controller
{


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $events = Event::all();
        foreach ($events as $event) {
            $event->date = date_format(date_create($event->date), "d.m.Y");
        }
        return view('events.index')->with('events', $events);
    }

    public function apiIndex()
    {
        return Event::with('sessions')->get();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('events.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $event = new Event($request->except('sessions'));

        $event->save();
        if (isset($request->sessions)) {
            foreach ($request->sessions as $session) {
                $sessionEntity = new Session($session);
                $event->sessions()->create($sessionEntity->toArray());
            }

        }
        return redirect()->route('events.show', ['event' => $event->id])->with('message', 'Event successfully created');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $event = Event::find($id);
        return view('events.detail')->with('event', $event)->with('message', 'Event successfully created');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $event = Event::find($id);
        return view('events.edit')->with('event', $event)->with('eventSessions', json_encode($event->sessions));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $event = Event::find($id);
        $event->update($request->except('sessions'));
        if ($event->sessions) {
            foreach ($event->sessions as $session) {
                $session->delete();
            }

        }
        if ($request->sessions) {
            foreach ($request->sessions as $session) {
                $session = new Session([
                    'id' => $session['id'],
                    'time' => $session['time'],
                    'title' => $session['title'],
                    'room' => $session['room'],
                    'speaker' => $session['speaker'],
                ]);
                $event->sessions()->create($session->toArray());
            }
        }
        return redirect()->route('events.show', ['event' => $event->id])->with('message', 'Event successfully saved');
    }

    public function showAttendeeList()
    {
        return view('events.attendees',['users' => User::all()]);
    }

    public function showEventRating(Request $request, Event $event)
    {
        return view('events.rating', ['ratings' => $event->ratings->filter(function ($rating) {
            return isset($rating->event_rating);
        })]);
    }
}

backend/resources/views/events/attendees.blade.php
@extends('layouts.app')
@section('content')
<div>
    <div class="header">
        <h1>Attendees Events</h1>
        <a class="btn btn-primary" id="add-event" href="/events">Back to events</a>
    </div>
    <div>
        <table>
            <thead>
            <tr>
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Email</th>
                <th>Photo</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($users as $user)
                <tr>
                    <td>{{$user->firstname}}</td>
                    <td>{{$user->lastname}}</td>
                    <td>{{$user->email}}</td>
                    <td><img src="{{$user->photo_url}}" alt="" style="width: 150px;"></td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection

backend/resources/views/events/create.blade.php
@extends('layouts.app')
@section('content')

<div class="header">
    <h1>Create new event</h1>
</div>

<div class="body">
    <form method="POST" action="/events">
        @csrf
        <div class="col-sm-6">
            <label for="title">Title</label>
            <input class="form-control" id="title" type="text" name="title">
        </div>

        <div class="col-sm-6">
            <label for="description">Description</label>
            <textarea class="form-control" id="description" name="description"></textarea>
        </div>

        <div class="col-sm-6">
            <label for="date">Date</label>
            <input class="form-control" id="date" type="date" name="date">
        </div>

        <div class="col-sm-6">
            <label for="time">Time</label>
            <input class="form-control" id="time" type="time" name="time">
        </div>

        <div class="col-sm-6">
            <label for="duration_days">Duration (days)</label>
            <input class="form-control" id="duration_days" type="number" name="duration_days">
        </div>

        <div class="col-sm-6">
            <label for="location">Location</label>
            <input class="form-control" id="location" type="text" name="location">
        </div>

        <div class="col-sm-6">
            <label for="standard_price">Price</label>
            <input class="form-control" id="standard_price" type="number" name="standard_price">
        </div>

        <div class="col-sm-6">
            <label for="capacity">Capacity</label>
            <input class="form-control" id="capacity" type="number" name="capacity">
        </div>

        <div class="col-sm-8">
            <label>Sessions</label>
                <session-component></session-component>
        </div>

        <div class="col-sm-6">
            <button class="btn btn-success" type="submit" id="create-event">
                Create
            </button>
        </div>
    </form>
</div>

@endsection

backend/resources/views/events/detail.blade.php
@extends('layouts.app')
@section('content')
<div class="header">
    <h1>Event</h1>
</div>
@if (session('message'))
    <span class="text-success text-bold">{{session('message')}}</span>
@endisset
<div class="body">
    <table>
        <tbody>
            <tr>
                <th>Title</th>
                <td class="event-title">{{$event->title}}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td class="event-description">{{$event->description}}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td class="event-date">{{$event->date}}</td>
            </tr>
            <tr>
                <th>Time</th>
                <td class="event-time">{{$event->time}}</td>
            </tr>
            <tr>
                <th>Duration (days)</th>
                <td class="event-duration-days">{{$event->duration_days}}</td>
            </tr>
            <tr>
                <th>Location</th>
                <td class="event-location">{{$event->location}}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td class="event-price">{{$event->standard_price}}</td>
            </tr>
            <tr>
                <th>Capacity</th>
                <td class="event-capacity">{{$event->capacity}}</td>
            </tr>
            <tr>
                <th>Sessions</th>
                <td class="event-sessions">
                            <table>
                                <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Time</th>
                                    <th>Location</th>
                                    <th>Speaker</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($event->sessions as $session)
                                <tr>
                                    <td>{{$session->title}}</td>
                                    <td>{{$session->time}}</td>
                                    <td>{{$session->room}}</td>
                                    <td>{{$session->speaker}}</td>
                                </tr>
                                @endforeach
                                </tbody>
                            </table>
                </td>
            </tr>
        </tbody>
    </table>
</div>
<br><br>
<a class="btn btn-warning" id="edit-event" href="{{route('events.edit', $event->id)}}">Edit event</a>

@endsection

backend/resources/views/events/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="header">
    Edit event
</div>

<div class="body">
    <form method="POST" action="{{route('events.update', $event->id)}}">
        @csrf
        @method('PUT')
        <div class="col-sm-6">
            <label for="title">Title</label>
            <input class="form-control" id="title" type="text" value="{{$event->title}}" name="title">
        </div>

        <div class="col-sm-6">
            <label for="description">Description</label>
            <textarea class="form-control" id="description"  name="description">{{$event->description}}</textarea>
        </div>

        <div class="col-sm-6">
            <label for="date">Date</label>
            <input class="form-control" id="date" type="date" value="{{$event->date}}" name="date">
        </div>

        <div class="col-sm-6">
            <label for="time">Time</label>
            <input class="form-control" id="time" type="time" value="{{$event->time}}" name="time">
        </div>

        <div class="col-sm-6">
            <label for="duration_days">Duration (days)</label>
            <input class="form-control" id="duration_days" type="number" value="{{$event->duration_days}}" name="duration_days">
        </div>

        <div class="col-sm-6">
            <label for="location">Location</label>
            <input class="form-control" id="location" type="text" name="location" value="{{$event->location}}">
        </div>

        <div class="col-sm-6">
            <label for="standard_price">Price</label>
            <input class="form-control" id="standard_price" type="number" name="standard_price" value="{{$event->standard_price}}">
        </div>

        <div class="col-sm-6">
            <label for="capacity">Capacity</label>
            <input class="form-control" id="capacity" type="number" name="capacity" value="{{$event->capacity}}">
        </div>

        <div class="col-sm-8">
            <label>Sessions</label>
            <div id="edit-sessions" data-sessions="{{$eventSessions}}">
                <session-component></session-component>
            </div>
        </div>

        <div class="col-sm-6">
            <button class="btn btn-success" type="submit" id="create-event">
                Save
            </button>
        </div>
    </form>
</div>
@endsection

backend/resources/views/events/index.blade.php
@extends('layouts.app')
@section('content')
<div class="header">
    <h1>Events</h1>
    <a class="btn btn-success" id="add-event" href="/events/create">Add event</a>
</div>

<div class="content">
    <table class="table">
        <thead>
            <tr>
                <th>Event</th>
                <th>Date</th>
                <th>Price</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($events as $event)
            <tr class="event">
                <td class="event-title">
                    <a href="{{route('events.show', ['event' => $event->id])}}">{{$event->title}}</a>
                </td>
                <td class="event-date">{{$event->date}}</td>
                <td class="event-price">{{$event->standard_price}}</td>
                <td class="event-actions">
                    <a class="event-participants" href="{{route('events.attendees', ['event'=> $event->id])}}">Attendee list</a>
                    <a class="event-participants" href="{{route('events.rating', ['event'=> $event->id])}}">Ratings</a>
                </td>
            </tr>
            @endforeach

        </tbody>
    </table>
</div>
@endsection

backend/resources/views/events/rating.blade.php
@extends('layouts.app')
@section('content')
<div>
    <div class="header">
        <h1>Event Rating</h1>
        <a class="btn btn-primary" id="add-event" href="/events">Back to events</a>
    </div>
    <rating-chart id="ratingChart" data-chart-data="{{$ratings}}"></rating-chart>
</div>
@endsection